### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NeihTzxc** [joeygoksu/prime-nestjs#13]
**Describe the bug**
Docker-Compose not installed when install docker compose

**To Reproduce**
Steps to reproduce the behaviour:
1. run bash ./setup.sh

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Docker version 20.10.22
 - Docker Compose version v2.14.1

**Comment by joeygoksu** [comment]
@NeihTzxc Can you please provide the error code/message or a screenshot?

**Comment by NeihTzxc** [comment]
![image](https://user-images.githubusercontent.com/45267625/222997855-27dcef73-90ab-4f85-83d0-bd05fe93bdb8.png)

**Comment by NeihTzxc** [comment]
Docker Compose version v2.14. In docker compose 2 version, change from docker-compose to docker compose. Please update docker compose from version 1 to version 2. Currently docker compose version 1 is no longer available on Ubuntu 22.04 and later versions.
